parameters:
#    vgc_main.example.class: Vgc\MainBundle\Example

services:
#    vgc_main.example:
#        class: %vgc_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
