<?php

namespace Vgc\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Support_RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRegionRepository extends EntityRepository {

}
